# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29401cb8318ac81341be0b4b3fc06c989226e564743f30cf144779bf325cfa79a78ae1dfa75043004b6435e095ba10fe42c192d0d3fe6a984bb121437116b6b5

test:
  secret_key_base: cdf6ad85265517b23d17b945f0201de736d2ad26d8ba7d15100d630481fc2414bb79dcc329b291390099947ad6fb16a2bc7277a77d203b4762ddba57a4f4a718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
